### ISSUE TITLE
Can't add a Utility meter because doesn't show any options

### ISSUE THREAD

**Issue by designerferro** [dgomes/ha_erse#1]
Installer in Hass.io via Community addons. 

In the integrations, added the ERSE integration.

The pull down meny for the Utility metter shows no options and doesnt allow you to add manual values.

**Comment by dgomes** [comment]
Vou escrever em Portugues pq este componente é só mesmo para nós :)

Aparece alguma entidade utility_meter.* no menu developers tools -> state ?

**Comment by designerferro** [comment]
Não tinha percebido da documentação que tinha de ter um utility_meter. Entendi que era apenas um valor extraído/scrapped do site da ERSE. 

Já percebi que tinha de ter a integração https://www.home-assistant.io/integrations/utility_meter/.

De momento não tenho nenhuma origem de consumos instalada.

**Comment by dgomes** [comment]
O componente fornece o estado da tarifa (Vazio, Cheia, etc) e auxilia na automatização da troca de tarifas dos utility meters

Na realidade nem ha qualquer scrapping envolvido pq as tarifas/horarios são as mesmas para todos os operadores registados junto da ERSE

**Comment by csrui** [comment]
> Não tinha percebido da documentação que tinha de ter um utility_meter. Entendi que era apenas um valor extraído/scrapped do site da ERSE.
> 
> Já percebi que tinha de ter a integração [home-assistant.io/integrations/utility_meter](https://www.home-assistant.io/integrations/utility_meter/).
> 
> De momento não tenho nenhuma origem de consumos instalada.

Apanhar aqui boleia... :)
Há forma de utilizar um utility meter com a EDP?

**Comment by dgomes** [comment]
Claro, eu uso com a EDP :)

**Comment by csrui** [comment]
Mas o registo é feito de forma manual ou automatica? Como é que tens isso?

**Comment by dgomes** [comment]
Este componente não faz os registos das leituras, apenas as trata. No meu caso tenho um equipamento de medição de energia que me serve de fonte ao meu utility_meter.

Leituras manuais, acho q seria desagradável... melhor é apostares num equipamento de medição.

**Comment by csrui** [comment]
Podes-me dizer qual é o equipamento ou partilhar algum link? Foste tu que fizeste a instalação desse equipamento?

**Comment by dgomes** [comment]
@csrui estamos a ficar offtopic, convido-te a dar uma salto a: https://cpha.pt
