### ISSUE TITLE
Error setting up entry goldenergy_bi_horario_ciclo_diario for erse

### ISSUE THREAD

**Issue by vdiogo** [dgomes/ha_erse#13]
Bom dia

Tenho um erro a carregar esta integração, e nos logs esta é a informação que tenho:

Logger: homeassistant.config_entries
Source: custom_components/erse/__init__.py:36 
Integration: Entidade Reguladora dos Serviços Energéticos (documentation, issues) 
First occurred: 12:37:51 (1 occurrences) 
Last logged: 12:37:51

Error setting up entry goldenergy_bi_horario_ciclo_diario for erse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/erse/__init__.py", line 36, in async_setup_entry
    entry.data[CONF_INSTALLED_POWER],
KeyError: 'installed_power'

Tenho:
Versão: HA core-2021.8.6
Versão do Supervisor | supervisor-2021.06.8

**Comment by dgomes** [comment]
experimenta remover o ERSE e voltar a configurar (ele queixa-se q não configuraste a potencia instalada)

**Comment by vdiogo** [comment]
Boa!
