### ISSUE TITLE
Can't set prices

### ISSUE THREAD

**Issue by nunofgs** [dgomes/ha_erse#17]
I'm on HASS 2021.10.5 and installed ERSE through HACS. When I get to the step of inputting prices, I can't type: `0.098`.

<img width="405" alt="Screenshot 2021-10-16 at 22 39 09" src="https://user-images.githubusercontent.com/92085/137602728-c37d6056-a43a-47e0-923d-907b31c0ac62.png">

The input fields don't accept leading zeroes.

**Comment by dgomes** [comment]
This seams related to HA frontend

I've created https://github.com/home-assistant/frontend/issues/10308
