### ISSUE TITLE
Reset Energy Cost Todos os meses 

### ISSUE THREAD

**Issue by bombastikk** [dgomes/ha_erse#18]
Bom dia 

Gostaria da vossa ajuda , para perceber a razão porque o sensor do custo não volta a 0 todos os inicios dos meses
![cost](https://user-images.githubusercontent.com/70980928/140048214-12b0e005-a869-4ea6-9800-a13475da60a1.PNG)

**Comment by dgomes** [comment]
Tens q partilhar a tua configuração (nomeadamente a configuração do utility_meter configurado no ERSE)

**Comment by bombastikk** [comment]
utility_meter:
  hourly_energy:
    source: sensor.quadro_energy
    cycle: hourly
    tariffs:
      - Fora de Vazio
      - Vazio
        
  daily_energy:
    source: sensor.quadro_energy
    cycle: daily
    tariffs:
      - Fora de Vazio
      - Vazio  
 
  weekly_energy:
    source: sensor.quadro_energy
    cycle: weekly
    tariffs:
      - Fora de Vazio
      - Vazio      

  monthly_energy:
    source: sensor.quadro_energy
    cycle: monthly
    tariffs:
      - Fora de Vazio
      - Vazio      

  bimonthly_energy:
    source: sensor.quadro_energy
    cycle: bimonthly
    tariffs:
      - Fora de Vazio
      - Vazio      
      
  yearly_energy:
    source: sensor.quadro_energy
    cycle: yearly
    tariffs:
      - Fora de Vazio
      - Vazio   
  
![cost2](https://user-images.githubusercontent.com/70980928/140051708-df33aec1-8786-45ea-8817-f6489118ece8.PNG)
![cost1](https://user-images.githubusercontent.com/70980928/140051713-709c0d75-6b10-4caf-8cd7-2423b82caa15.PNG)

**Comment by dgomes** [comment]
Tens ai muitos utility_meters... qual é que configuraste no ERSE ?

**Comment by bombastikk** [comment]
eu configurei o sensor.quadro_energy que está a lêr um Shelly 3M

eu configurei os outros utilitys metters para ter a informação diaria/ semanal /mensal 

Se não for esta informação que necessitas , podes me indicar onde vejo ?

Obrigado pelas respostas

**Comment by dgomes** [comment]
Quando configuraste o ERSE ele pediu para indicares um utility_meter, é esse que procuro conhecer (não dá para ver depois de configurado)

O utility_meter configurado no ERSE tem que ser um mensal

**Comment by bombastikk** [comment]
Posso Remover e voltar a adicionar , queres que faça e tiro os prints ?

**Comment by dgomes** [comment]
sim sff

**Comment by bombastikk** [comment]
Segue as configurações : no segundo print que metter devo escolher
![cost3](https://user-images.githubusercontent.com/70980928/140060929-4436116d-5d66-4af0-8363-fb4dfa2f2c53.PNG)
![cost4](https://user-images.githubusercontent.com/70980928/140060943-d4ad023a-d363-4496-9631-1d33c761dc0d.PNG)
 ?

**Comment by dgomes** [comment]
escolheste qual ? (espero que o `utility_meter.monthly_energy`)

**Comment by bombastikk** [comment]
Não escolhi , estava a espera da confirmação tua , vou definir agora

**Comment by bombastikk** [comment]
Já agora os sensores estão correctos assim 
![cost5](https://user-images.githubusercontent.com/70980928/140065841-0225205d-e5f1-4a70-aa66-5246633dc276.PNG)
?

**Comment by dgomes** [comment]
tudo ok

**Comment by bombastikk** [comment]
Obrigado pela ajuda 

Deixo uma recomendação no teu how to no repositorio ,devias ter uns prints para a malta se orientar :)

Ultima pergunta como é que o sensor do cost vai passar para 0 ?

**Comment by dgomes** [comment]
Podes abrir um Pull Request e contribuir :)

O custo vai a 0 quanto o utility_meter for a 0

**Comment by jmcg0** [comment]
Bom dia,

Comecei a usar o ERSE à coisa de 1 mês e reparei que a data de passagem a zero não coincide com a data de faturação da EDP (a da EDP ocorre 3 dias antes). Há alguma forma de ajustar a data de reset (passagem a zero) do utility meter ? Obrigado

**Comment by dgomes** [comment]
> Bom dia,
> 
> Comecei a usar o ERSE à coisa de 1 mês e reparei que a data de passagem a zero não coincide com a data de faturação da EDP (a da EDP ocorre 3 dias antes). Há alguma forma de ajustar a data de reset (passagem a zero) do utility meter ? Obrigado

Sim com o `offset`

https://www.home-assistant.io/integrations/utility_meter/#offset

**Comment by jmcg0** [comment]
Obrigado dgomes,

A questão é que no configuration.yaml não tenho qualquer utility meter definido:
![image](https://user-images.githubusercontent.com/77812867/170488974-17796a91-b77b-4670-ba30-4bf70203b53c.png)

No entanto tenho utility meters:
![image](https://user-images.githubusercontent.com/77812867/170489125-b4336ddf-7266-47a2-adb1-7586983322ab.png)

E de fato existe um campo que aponta para o dia de reset (19) mas que no meu caso deveria estar a indicar 16 (dia da contagem da EDP):
![image](https://user-images.githubusercontent.com/77812867/170488690-96f05f51-5a3d-4bbe-b5a6-978e3ce9b32d.png)

Não sei se no processo de setup do ERSE isto foi configurado de forma automática mas já "corri" os ficheiros de "custom components\erse" e não encontro nenhuma indicação/sitio para colocar a data.

Obrigado,

**Comment by dgomes** [comment]
Se não está no YAML quer dizer que configuraste o utility meter via UI, na mesma UI podes definir o offset:

<img width="584" alt="Screenshot 2022-05-26 at 13 52 36" src="https://user-images.githubusercontent.com/137684/170491333-c6fa33ba-35b5-484c-bcea-ff9a34472c07.png">

**Comment by jmcg0** [comment]
Onde é que no UI posso fazer isso ?

**Comment by dgomes** [comment]
É no momento que configuras o utility_meter... teras que o apagar e criar de novo agora

**Comment by jmcg0** [comment]
Tenho que olhar para as instruções de instalação do ERSE novamente...se fizer isso perco as contagens dos meses anteriores ?

**Comment by dgomes** [comment]
O problema nao é o ERSE, o problema é o utility_meter.... 

Por acaso, se apagar o utility_meter e criar um novo com o mesmo nome, deverá "recuperar" os registos antigos (nao testei)

**Comment by helderfmf** [comment]
@jmcg0 
Para quem é aventureiro, pode-se alterar os items criados pelo UI na configuração interna do HA, visto que não se consegue alterar a maior parte das configurações via UI.
Basta ir com o File Editor, ou outro editor de texto, ao ficheiro `/config/.storage/core.config_entries` e alterar lá o "offset":
![image](https://user-images.githubusercontent.com/5622687/222154220-224ab38f-52f2-44b1-bcd3-7f37565a7a2e.png)
Um restart e já fica com as novas configurações.
**É preciso ter muito cuidado ao editar este ou qualquer outro ficheiro dentro da pasta `/config/.storage` , pois é, a config "core" do HA.**
