### ISSUE TITLE
Tarifas Operador SU Electricidade

### ISSUE THREAD

**Issue by rockas69** [dgomes/ha_erse#19]
Would it be possible to add power operator SU Electricidade?
https://sueletricidade.pt/pt-pt/page/601/tarifas-baixa-tensao-normal

**Comment by dgomes** [comment]
Na versão actual não ha qq dependência em operadores...  Pode colocar o nome que quiser, são suportados as potencias e horários definidos pela ERSE para todos operadores

**Comment by rockas69** [comment]
Esta ainda está válida ou será melhor usar a nova versão ERSE que está publicada do CPHA? Contudo, não a encontro no Configurations -> Integrations.

**Comment by dgomes** [comment]
Esta página tem sempre a ultima versão que deve ser instalada via HACS

**Comment by rockas69** [comment]
Colocar como repositório?

**Comment by dgomes** [comment]
Podes colocar como repositorio sim
