### ISSUE TITLE
Com a atualização de ontem, a tarifa não mudou ás 0:00.

### ISSUE THREAD

**Issue by cassisn** [dgomes/ha_erse#20]
Boas,

Fiz ontem a atualização do Etse, hoje reparei que ás 00:00 não mudou a tarifa, manteve a Tarifa fora de vazio. Obrigado.

**Comment by dgomes** [comment]
Estas na 2.1.3 ?

**Comment by dgomes** [comment]
fixed na versão 2.1.4

**Comment by cassisn** [comment]
Já a atualizei para a 2.1.4, vou ter de reconfigurar, certo? Obrigado

**Comment by dgomes** [comment]
Sim é necessario reconfigurar pois agora é necessário usar as entidades `select.*` e não as `utility_meter.*`
