### ISSUE TITLE
O sensor não é mostrado para escolher quando estou a colocar a tarifa e o sensor de vazio e fora de vazio

### ISSUE THREAD

**Issue by cassisn** [dgomes/ha_erse#21]
Já fiz a atualização para a última versão, apaguei todas as entidades.
Algumas entidades não estão disponíveis para escolha quando estou a escolher o sensor para vazio e para fora de vazio.
Essas mesmas entidades existem, foram criadas, e aparentemente não têm erro.
Normalmente tenho 3 integrações ERSE:
1. EDP - Ciclo Diário - Bi-horário
2. EDP - Ciclo Semanal - Bi-horário
3. CASA - Ciclo Semanal - Bi-horário (serve para medir o que de facto consumo em casa, como tenho solar, serve para comparar com o que vou comprar à EDP)
Consegui criar as duas primeiras, sem problema. A terceira não, devido a não estarem disponiveis os respectivos meteres para escolha.
Existe alguma limitação em termos da integração que deva atender?
NOTA: Esteve a funcionar anteriormente.
Obrigado

**Comment by dgomes** [comment]
Existe algum erro nos logs ? Pode partilhar configuração do utility_meter e print screen do que aparece quando esta a configurar o CASA ?

**Comment by cassisn** [comment]
Encontrei este erro:

![Captura de ecrã 2022-04-13 223319](https://user-images.githubusercontent.com/81772454/163276426-620f0b75-30f4-47fc-82f7-0f474074db46.png)


Aqui não surgem os meters

![Captura de ecrã 2022-04-13 224529](https://user-images.githubusercontent.com/81772454/163276285-bea7324d-63c9-46f9-840c-200494d6af59.png)

Parece-me que o problema está relacionado com os erros dos logs, não sei é como resolver.
Obrigado

**Comment by dgomes** [comment]
O log diz especificamente o que tem que fazer para resolver....

**Comment by cassisn** [comment]
Desculpa mas só agora consegui responder.
No browser retorna 404 - not found quando coloco
https://xx.xx.xx.xx:8123/redirect/developer_statistics
