### ISSUE TITLE
Adicionar novo Operador dos Açores

### ISSUE THREAD

**Issue by gajotnt** [dgomes/ha_erse#22]
Boas, sou dos açores, lá temos apenas a EDA como fornecedor de electricidade.
Depois de alguma pesquisa deparei-me com este projecto, que me parece muito interessante e funcional.

E gostava de saber se seria possível, inserir este tarifário trihorario que acaba por ser um bocado complicado pk sábado e domingo é diferente do resto da semana e o ano está dividido em 2 partes com alterações nas horas.

![Screenshot_20211003-232813_2](https://user-images.githubusercontent.com/25504364/176429199-2e3f4b03-22b7-42cb-aece-72a703dece5b.jpg)

Caso não seja possível, compreendo e fico agradecido na mesma :)

Obrigado pela atenção

**Comment by gajotnt** [comment]
Agora q diz e fui ver, sim é parecido com algumas alterações nas horas

Sendo que ja existe a base de código, não tenhos muitos conhecimentos mas posso tentar fazer um submit de code com os horários para os Açores se me disser qual o ficheiro que tem essas informações :)


![particulares_opcaohoraria_mediablock_tri_1024](https://user-images.githubusercontent.com/25504364/176463334-b0a349a3-65c1-4e4f-a7e8-a28c08cd797a.png)

**Comment by gajotnt** [comment]
Ahhh pá tive a procura e ler melhor, entao o leitor de energia já tem que ter essas informações dos horários.

Tenho q rever isso melhor e descobrir como se faz isso.
Obrigado e desculpe lá o mal entendido :)

**Comment by gajotnt** [comment]
Pois... é a magia dos Açores lolol

**Comment by Null-Mind** [comment]
Mais um dos Acores aqui ... no meu caso uso a Tarifa tripla ou tri-horária, e como podem ver e diferente ligeiramente da EDP

Existe como eu editar os horários das tarifas ?

![6129243_orig](https://github.com/user-attachments/assets/df8f8fc9-f57c-4f13-a1a8-2c276578e313)

**Comment by gajotnt** [comment]
> Mais um dos Acores aqui ... no meu caso uso a Tarifa tripla ou tri-horária, e como podem ver e diferente ligeiramente da EDP
> 
> Existe como eu editar os horários das tarifas ?
> 
> ![6129243_orig](https://private-user-images.githubusercontent.com/10864260/372235494-df8f8fc9-f57c-4f13-a1a8-2c276578e313.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mjg2MjQsIm5iZiI6MTcyNzcyODMyNCwicGF0aCI6Ii8xMDg2NDI2MC8zNzIyMzU0OTQtZGY4ZjhmYzktZjU3Yy00ZjEzLWExYTgtMmMyNzY1NzhlMzEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIwMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWQ3MGIxYmZhNmJhMmVhZmRjYzM3Yzk1NDk1ZjEzZjQ2MTFkYmE3ZWY0YjcwNjZjYThmYjAxODkwNWUwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vXMM310SLVu9trSpiMwdcgoOPspoFQ1wSsb7qpqSp4M) [ ![6129243_orig](https://private-user-images.githubusercontent.com/10864260/372235494-df8f8fc9-f57c-4f13-a1a8-2c276578e313.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mjg2MjQsIm5iZiI6MTcyNzcyODMyNCwicGF0aCI6Ii8xMDg2NDI2MC8zNzIyMzU0OTQtZGY4ZjhmYzktZjU3Yy00ZjEzLWExYTgtMmMyNzY1NzhlMzEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIwMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWQ3MGIxYmZhNmJhMmVhZmRjYzM3Yzk1NDk1ZjEzZjQ2MTFkYmE3ZWY0YjcwNjZjYThmYjAxODkwNWUwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vXMM310SLVu9trSpiMwdcgoOPspoFQ1wSsb7qpqSp4M) ](https://private-user-images.githubusercontent.com/10864260/372235494-df8f8fc9-f57c-4f13-a1a8-2c276578e313.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mjg2MjQsIm5iZiI6MTcyNzcyODMyNCwicGF0aCI6Ii8xMDg2NDI2MC8zNzIyMzU0OTQtZGY4ZjhmYzktZjU3Yy00ZjEzLWExYTgtMmMyNzY1NzhlMzEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIwMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWQ3MGIxYmZhNmJhMmVhZmRjYzM3Yzk1NDk1ZjEzZjQ2MTFkYmE3ZWY0YjcwNjZjYThmYjAxODkwNWUwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vXMM310SLVu9trSpiMwdcgoOPspoFQ1wSsb7qpqSp4M) [ ](https://private-user-images.githubusercontent.com/10864260/372235494-df8f8fc9-f57c-4f13-a1a8-2c276578e313.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mjg2MjQsIm5iZiI6MTcyNzcyODMyNCwicGF0aCI6Ii8xMDg2NDI2MC8zNzIyMzU0OTQtZGY4ZjhmYzktZjU3Yy00ZjEzLWExYTgtMmMyNzY1NzhlMzEzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIwMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWQ3MGIxYmZhNmJhMmVhZmRjYzM3Yzk1NDk1ZjEzZjQ2MTFkYmE3ZWY0YjcwNjZjYThmYjAxODkwNWUwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vXMM310SLVu9trSpiMwdcgoOPspoFQ1wSsb7qpqSp4M)

https://forum.cpha.pt/t/alternativa-a-integracao-erse-usando-helpers-e-template/12169

**Comment by Null-Mind** [comment]
Eu estou a utilizar os helpers e funciona, mas queria fazer esta integração funcionar para poder fazer certos cards, eu penso que vi em algum lugar que foi feito um pyerse para os açores mas precisa de testar, mas nao encontro o post que o vi ...

**Comment by dgomes** [comment]
É preciso alterar o pyerse e depois o ha_erse
