### ISSUE TITLE
Feature Request: Sum of all tariffs and costs for each cycle (utility_meter)

### ISSUE THREAD

**Issue by FragMenthor** [dgomes/ha_erse#24]
Automatically create 2 more sensors, for each utility_meter:
 - Sum of energy of all tariffs
 - Sum of cost for all tariffs
 
Then it would be possible to have, automatically, without doing templates: daily / monthly consuptions and costs, derived from the sum of the tariffs for each cycle.
I think this would improve a lot this integration, because everyone that uses it the right way will have to always do this template sensors "by hand".
Thanks again :)

**Comment by dgomes** [comment]
Added in 0a28deb
