### ISSUE TITLE
Arredondamento de casas decimais

### ISSUE THREAD

**Issue by jdserras** [dgomes/ha_erse#32]
Após atualização do HA passei a não ter arredondamento das casas decimais e o "Round" não é aceite na configuração. Como poderei definir o máximo de casas decimais?
Obrigado.

**Comment by dgomes** [comment]
click na entidade, no canto superior direito tens uma engrenagem

**Comment by jdserras** [comment]
No meu caso apenas tenho esta opção:

 



 

De: Diogo Gomes ***@***.***> 
Enviada: 3 de julho de 2023 15:39
Para: dgomes/ha_erse ***@***.***>
Cc: João Serrasqueiro ***@***.***>; Author ***@***.***>
Assunto: Re: [dgomes/ha_erse] Arredondamento de casas decimais (Issue #32)

 

click na entidade, no canto superior direito tens uma engrenagem

**Comment by dgomes** [comment]
para colocar screenshots tem q usar o site (não dá para responder por email)

**Comment by jdserras** [comment]
![image](https://github.com/dgomes/ha_erse/assets/77854423/d6da2986-0593-4464-81ae-a9f841911921)

**Comment by jdserras** [comment]
Atualizei tudo este fim de semana e já estou arrependido 😊

 

De: Diogo Gomes ***@***.***> 
Enviada: 3 de julho de 2023 15:49
Para: dgomes/ha_erse ***@***.***>
Cc: João Serrasqueiro ***@***.***>; Author ***@***.***>
Assunto: Re: [dgomes/ha_erse] Arredondamento de casas decimais (Issue #32)

 

engrenagem está lá :)

Mas está na hora de actualizar esse Home Assistant tb ....

**Comment by dgomes** [comment]
Estava a olhar para isto... o daily_energy é um sensor do utility_meter, certo ?

**Comment by jdserras** [comment]
Sim, certo.

Sent by Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by dgomes** [comment]
Pois... isso pertence ao HA mesmo
