### ISSUE TITLE
From self.async_update_ha_state() to self.async_write_ha_state()

### ISSUE THREAD

**Issue by ostracizado** [dgomes/ha_erse#33]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:705
First occurred: 13:41:25 (1 occurrences)
Last logged: 13:41:25

Entity sensor.edp_4_6_kva_bi_horaria_ciclo_semanal (<class 'custom_components.erse.sensor.EletricityEntity'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

**Comment by dgomes** [comment]
fixed in the latest release
