### ISSUE TITLE
Error in LOG after upgrading to the latest version

### ISSUE THREAD

**Issue by Joao-Sousa-71** [dgomes/ha_erse#34]
Upgrade done using HACS teh Delete the old configuration and create a new one.
HA version: 2023.9.2
ERSE Version 2.2.0

Log error
`2023-09-22 23:49:12.080 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up erse platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/erse/sensor.py", line 79, in async_setup_entry
    TariffCost(hass, config_entry.entry_id, tariff, meter_entity)
  File "/config/custom_components/erse/sensor.py", line 419, in __init__
    self._attr_name = hass.states.get(meter_entity).attributes.get("friendly_name")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'`

The entities were created

![image](https://github.com/dgomes/ha_erse/assets/76400918/6d66b7e5-acc7-406a-812e-9081220440ad)

But after a HA restart, they are no longer available:

![image](https://github.com/dgomes/ha_erse/assets/76400918/968c392b-c126-478d-8082-3157d32c5f2c)

And then with a reload they seem to be available again:

![image](https://github.com/dgomes/ha_erse/assets/76400918/30b8d918-0bdc-41cb-a0a5-4327fa81d9bd)

Thank you for this awesome component!

**Comment by dgomes** [comment]
Parece ser um problema com o teu `source_meter`

Podes verificar se ele tem um nome atribuído ou usa o default ?

**Comment by dgomes** [comment]
Sera que podes utilizar a ultima versão "beta" ? (é preciso ir as configurações do HACS escolher "beta")

**Comment by Joao-Sousa-71** [comment]
Duarte, obrigado pela ajuda/resposta :-)
A mim apareceu-me a V2.20 no HACS sem selecionar a opção de Beta e e entretanto o Nikito também me aconselhou o mesmo e vou experimentar agora

O meus Utility Meters estão criados no configuration.yaml desta forma

`  han_daily_total_energy_consumed:
    source: sensor.eb3_import
    cycle: daily
    tariffs:
      - Fora de Vazio
      - Vazio
  han_monthly_total_energy_consumed:  
    source: sensor.eb3_import
    cycle: monthly
    offset:
      days: 4
    tariffs:
      - Fora de Vazio
      - Vazio   `
em que o sensor.eb3_import é gerado pelo atraves do EasyHan.

Ja te digo alguma coisa.
Obrigado.

**Comment by Joao-Sousa-71** [comment]
Instalei a beta:

![image](https://github.com/dgomes/ha_erse/assets/76400918/f9ec4812-f980-4230-b586-194de92d0711)

Depois reiniciei o HA e configurei o Componente:

![image](https://github.com/dgomes/ha_erse/assets/76400918/6ab19f9f-8073-47fa-bd7a-657d5571be24)

![image](https://github.com/dgomes/ha_erse/assets/76400918/aafc1572-312e-4ee9-931c-8053dd7e8e1f)

![image](https://github.com/dgomes/ha_erse/assets/76400918/b7c4eb5b-1d58-4099-abfa-80a7563b377b)

Os sensores são criados mas ficam em estado 'unknown'

![image](https://github.com/dgomes/ha_erse/assets/76400918/93d07c95-6e93-4556-a061-a6a2ab3999e5)

E depois se reinicio o HA tenho a mesmo erro no Log:

`2023-09-23 22:37:30.684 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up erse platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/erse/sensor.py", line 79, in async_setup_entry
    TariffCost(hass, config_entry.entry_id, tariff, meter_entity)
  File "/config/custom_components/erse/sensor.py", line 419, in __init__
    self._attr_name = hass.states.get(meter_entity).attributes.get("friendly_name")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'`

e apos reiniciar os sensores ficam assim

![image](https://github.com/dgomes/ha_erse/assets/76400918/87ef1b5d-3ccc-4c5e-a066-3081c7499294)

Fiz a mesma configuração que tinha com a 2.1.7.
Ideias?

**Comment by dgomes** [comment]
<img width="612" alt="Screenshot 2023-09-23 at 23 01 21" src="https://github.com/dgomes/ha_erse/assets/137684/293bfb0e-1afc-49d0-a904-f4e8e7f8d7a4">

Quando activas a opção BETA surge uma versão "master" é essa que tens q instalar

**Comment by nikito7** [comment]
Sensores criados de raiz funciona.

![Screenshot_20230923_230941_Home Assistant](https://github.com/dgomes/ha_erse/assets/45373783/5813a2b8-6805-49b5-bfd3-a2349dd8a8cc)

**Comment by Joao-Sousa-71** [comment]
Duarte e Nikito, depois de instalar a Beta (selecionando a Master), começou a funcionar :-)
Nem foi preciso executar a configuração de novo:

![image](https://github.com/dgomes/ha_erse/assets/76400918/69e03268-d9ef-4803-9037-d9d0211eefe2)

Ainda faltam 12 dias e a conta ja vai alta :-D e estamos no verão!
Obrigado a ambos e bom resto de fim de semana!
Vou fechar a issue.
