### ISSUE TITLE
Inserir 0 à direita de um número nas tarifas

### ISSUE THREAD

**Issue by pixolex** [dgomes/ha_erse#36]
Não é possível inserir 0 à direita de um número nas tarifas (cheia, ponta, vazio) da integração ERSE.
Tenho que escrever um número qualquer, mudar o cursor para antes desse número e então inserir o 0.
Por exemplo 0.101, não se consegue escrever sem ser primeiro 0.11 e depois mover o cursor e colocar o 0 no meio dos 1

**Comment by dgomes** [comment]
Erro de frontend,

Tenta fazer o mesmo uma outra integração oficial

abrir em https://github.com/home-assistant/frontend
