### ISSUE TITLE
No module named 'pyerse'

### ISSUE THREAD

**Issue by lobmarib** [dgomes/ha_erse#40]
Boa tarde,
actualizei para a última versão de ha core 2024.10.1 e comecei a ter o seguinte

`Setup failed for custom integration 'erse': Unable to import component: No module named 'pyerse'`

Não sei se foi coincidência acontecer com a actualização ou se já alguém teve o mesmo problema.

Obrigado

**Comment by dgomes** [comment]
bug do Home Assistant q nao consegue instalar a dependência, esperar pela próxima release intermedia

**Comment by lobmarib** [comment]
Nada que se posso fazer para forçar a instalação da dependência?

**Comment by dgomes** [comment]
se entrares no container do HA podes executar:

`uv pip install pyerse`

**Comment by dgomes** [comment]
Resolvido ? podemos fechar ?

**Comment by lobmarib** [comment]
Fixed using the provided workaround
