### ISSUE TITLE
so consigo uma entidade na integração

### ISSUE THREAD

**Issue by cabriltt** [dgomes/ha_erse#5]
Boa tarde
Depois de realizar a atualização da integração ERSE, so me cria uma entidade na primeira integração de cada utility_meter, o que leva a que só aquele componente mude a tarifa.
Pode por favor ajudar-me nesta situação?
Muito Obrigado

**Comment by dgomes** [comment]
o ERSE é suposto ser **só uma entidade**

Com a actualização, o que pode é controlar vários utility_meters em simultâneo (quando antes precisava de várias entidades ERSE)

**Comment by cabriltt** [comment]
Ok percebi
estava a fazer como tinha antes que era varias entidades.
Muito obrigado, vou configurar e testar.
