### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'erse'.

### ISSUE THREAD

**Issue by madeirab** [dgomes/ha_erse#8]
Since lastest version of HA+ (2021.3.4) that i'm getting this warning: 

hass                 | 2021-03-24 17:16:58 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'erse'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'erse'

When will this be available so that on a future upgrade of HA the erse integration wont stop working?

Regards, Bruno

**Comment by dgomes** [comment]
New version released (just adds version)
